import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const client=fs.readFileSync(new URL('../multiplayer-client.js',import.meta.url),'utf8');
function fixture(){let n=0;const timers=new Map(),sockets=[];class Socket{static OPEN=1;constructor(){this.handlers={};this.readyState=0;sockets.push(this)}addEventListener(k,f){this.handlers[k]=f}send(){}close(){this.readyState=3}event(k,msg){if(k==='open')this.readyState=1;this.handlers[k]?.(k==='message'?{data:JSON.stringify(msg)}:{});}}
 const c={window:{ECHOES_MULTIPLAYER_CONFIG:{serverUrl:'wss://test'}},WebSocket:Socket,console,performance:{now:()=>1000},setTimeout:(fn,delay)=>{timers.set(++n,{fn,delay});return n},clearTimeout:id=>timers.delete(id),queueMicrotask};vm.runInNewContext(client,c);return {m:c.window.EchoesMulti,sockets,timers};}
test('cold start survives 30 seconds and duplicate connect shares pending promise',async()=>{const f=fixture(),p=f.m.connect(),p2=f.m.connect();assert.equal(p,p2);assert.equal(f.sockets.length,1);assert.ok([...f.timers.values()].some(t=>t.delay===90000));assert.ok(![...f.timers.values()].some(t=>t.delay===30000));f.sockets[0].event('open');f.sockets[0].event('message',{type:'hello:ok',selfId:'me'});assert.equal(await p,true);assert.equal(f.timers.size,0);});
test('late messages and close from cancelled socket cannot reset new connection',async()=>{const f=fixture(),p=f.m.connect().catch(e=>e);const old=f.sockets[0];f.m.disconnect();const next=f.m.connect(),current=f.sockets[1];current.event('open');current.event('message',{type:'hello:ok',selfId:'new'});await next;old.event('message',{type:'hello:ok',selfId:'old'});old.event('close');await p;assert.equal(f.m.state.selfId,'new');assert.equal(f.m.connected,true);});
test('ambient acquisition scans drop to 10 Hz while active simulation stays 40 Hz',()=>{const s=fs.readFileSync(new URL('../multiplayer-server/server.js',import.meta.url),'utf8'),a=s.indexOf('let ambientSelectionAt='),b=s.indexOf('function flushMobDeltas',a);let scans=0,ticks=0,respawns=0;const p={id:'p',ready:true,clientMode:'world'},m={id:'m',state:'chase'};const c={Map,Math,SIM_TICK_MS:25,mobsBootstrapped:true,players:new Map([['p',p]]),authoritativeMobs:new Map([['m',m]]),buildAmbientAggroSelections:()=>{scans++;return new Map()},simulateMob:()=>ticks++,respawnMob:()=>respawns++};vm.createContext(c);vm.runInContext(s.slice(a,b),c);for(let t=0;t<1000;t+=25)c.simulateWorld(t);assert.equal(scans,10);assert.equal(ticks,40);c.players.clear();m.dead=true;m.respawnAt=1000;c.simulateWorld(1100);assert.equal(scans,10);assert.equal(respawns,1);});
