import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorldCombat} from '../multiplayer-server/world-combat.js';
function fixture(){let time=10000;const player=id=>({id,ready:true,clientMode:'world',x:1000,y:1000,hp:1000,maxHp:1000,shield:500,maxShield:500,stam:100,maxStam:200,a:Math.PI});const a=player('a'),b=player('b');b.x=1100;const players=new Map([['a',a],['b',b]]),messages=[];const c=createWorldCombat({players,send(){},broadcast:m=>messages.push(m),publicState:p=>({id:p.id,x:p.x,y:p.y,hp:p.hp}),safeZone:(x)=>x<500,width:22000,height:11000,now:()=>time});let seq=0;return {a,b,c,messages,hit:(e={})=>c.handle(a,{seq:++seq,events:[{targetId:'b',kind:'attack',damage:100,...e}]}),step:n=>{time+=n;c.advance(a);c.advance(b);}};}
test('duplicate combat packet and duplicate input cannot double damage or roll state back',()=>{const f=fixture();f.hit();assert.equal(f.b.hp,900);f.c.handle(f.a,{seq:1,events:[{kind:'attack',targetId:'b',damage:100}]});assert.equal(f.b.hp,900);const state=f.c.ingest(f.b,{seq:1,combatAck:0,x:800,y:800,hp:1000});assert.equal(state.hp,900);assert.equal(state.x,1100);assert.equal(f.c.ingest(f.b,{seq:1}),null);});
test('forced movement wins over active input, settles, then permits fresh movement',()=>{const f=fixture();f.hit({dx:280,stun:.6,duration:.4});f.step(200);const x=f.b.x;assert.ok(x>1100&&x<1380);const state=f.c.ingest(f.b,{seq:1,combatAck:1,x:100,y:100,hp:900});assert.equal(state.x,x);f.step(500);assert.equal(f.b.x,1380);assert.equal(f.b.forceMove,null);const stale=f.c.ingest(f.b,{seq:2,combatAck:0,x:1100,hp:1000});assert.equal(stale.x,1380);const fresh=f.c.ingest(f.b,{seq:3,combatAck:f.b.combatRevision,x:1385,hp:900});assert.equal(fresh.x,1385);});
test('several forced deltas accumulate from server endpoint, no snap back',()=>{const f=fixture();f.hit({dx:100});f.c.handle(f.a,{seq:2,events:[{kind:'control',targetId:'b',dx:120,stun:.1}]});f.step(1000);assert.equal(f.b.x,1320);});
test('safe areas, party members, dead players and matchmaking clients excluded',()=>{for(const change of [f=>f.a.x=100,f=>{f.a.partyId=f.b.partyId='p'},f=>f.b.hp=0,f=>f.a.clientMode='pvp']){const f=fixture();change(f);const hp=f.b.hp;f.hit();assert.equal(f.b.hp,hp);}});
test('invulnerability prevents damage and does not grant a control lease',()=>{const f=fixture();f.b.invulnUntil=11000;f.hit({dx:100});f.c.handle(f.a,{seq:2,events:[{kind:'control',targetId:'b',dx:100}]});assert.equal(f.b.hp,1000);assert.equal(f.b.x,1100);assert.ok(!f.b.forceMove);});
test('shield block, break and parry are resolved once by server',()=>{let f=fixture();f.b.block=true;f.hit();assert.equal(f.b.hp,1000);assert.equal(f.b.shield,360);f=fixture();f.b.block=true;f.b.parryWindowUntil=10200;f.hit({dx:200});assert.equal(f.b.hp,1000);assert.equal(f.b.shield,496);assert.ok(f.a.stunUntil>10000);assert.ok(!f.b.forceMove);f=fixture();f.b.block=true;f.hit({breakShield:true});assert.equal(f.b.shield,0);assert.equal(f.b.hp,900);});
test('mark and shield-break special states require an accepted hit lease',()=>{const f=fixture();f.c.handle(f.a,{seq:1,events:[{kind:'special',targetId:'b',mark:3,breakShield:true}]});assert.equal(f.b.shield,500);f.c.handle(f.a,{seq:2,events:[{kind:'attack',targetId:'b',damage:100},{kind:'special',targetId:'b',mark:3,breakShield:true}]});assert.equal(f.b.shield,0);assert.equal(f.c.snapshot(f.b).mark,3);});
test('attack geometry evaluates actual victim coordinate',()=>{const f=fixture();f.hit({shape:'circle',x:900,y:1000,r:30});assert.equal(f.b.hp,1000);f.hit({shape:'arc',x:1000,y:1000,a:0,range:130,arc:1});assert.equal(f.b.hp,900);});
test('shared geometry and cubic forced move primitives',()=>{const c=globalThis.EchoesCombat;assert.equal(c.contains({shape:'segment',x1:0,y1:0,x2:100,y2:0,r:5},{x:50,y:50,r:18}),false);assert.equal(c.contains({shape:'rect',x:0,y:0,a:0,forward:100,half:10},{x:50,y:0,r:18}),true);assert.deepEqual(c.forcePoint({startX:0,startY:0,x:100,y:0,max:.4},.4),{x:100,y:0,done:true});});
test('absolute tracking replaces an endpoint instead of adding it repeatedly',()=>{const f=fixture();f.hit({dx:100});for(let i=0;i<8;i++){f.c.handle(f.a,{seq:i+2,events:[{kind:'control',targetId:'b',x:1400,y:1000,duration:.25}]});f.step(25);}f.step(500);assert.equal(f.b.x,1400);});
test('attack shape origin is not interpreted as a force destination',()=>{const f=fixture();f.hit({shape:'circle',x:1100,y:1000,r:50,dx:100});f.step(500);assert.equal(f.b.x,1200);});
test('PVP armor and shield formulas have matching deterministic values',()=>{const C=globalThis.EchoesCombat;assert.equal(C.damageAfterArmor(100,.2),80);assert.equal(C.damageAfterArmor(100,1),55);assert.equal(C.shieldCost(100),140);assert.equal(C.shieldCost(1),12);const f=fixture();f.b.defenseReduction=.2;f.hit();assert.equal(f.b.hp,920);});
test('teleport is rejected during control and accepted with a fresh acknowledgement afterward',()=>{const f=fixture();f.hit({stun:.5});let s=f.c.ingest(f.b,{seq:1,combatAck:1,teleport:true,x:4000,y:4000});assert.equal(s.x,1100);assert.ok(!f.b.teleportSeq);f.step(600);s=f.c.ingest(f.b,{seq:2,combatAck:1,teleport:true,x:4000,y:4000});assert.equal(s.x,4000);assert.equal(f.b.teleportSeq,2);});
test('repeated wave impacts renew force from victim actual position, not old endpoint',()=>{
 const f=fixture(),C=globalThis.EchoesCombat;
 for(let i=0;i<5;i++){const x=f.b.x;f.hit({shape:'circle',x,y:f.b.y,r:32,range:1200,skillId:'dawnArc',dx:C.waveControl.force,stun:C.waveControl.stun,duration:C.forceDuration(180)});assert.equal(f.b.forceMove.startX,x);assert.equal(f.b.forceMove.x,x+180);f.step(110);}
 assert.equal(f.b.hp,500);assert.ok(f.b.x>1600);f.step(800);const end=f.b.x;assert.equal(f.c.ingest(f.b,{seq:1,combatAck:0,x:1100,y:1000}).x,end);
});
